[package]
name = "keysetrs"
version = "0.1.0"
authors = ["Timm Behner <behner@cs.uni-bonn.de>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0.21"
libusb = "0.3"
toml = "0.4"
error-chain = "0.11.0"
structopt = "0.1.5"
structopt-derive = "0.1.5"
